import { resolveEntity } from "@/server/domains/syllabus/syllabus.service";
import * as syllabusRepo from "@/server/domains/syllabus/syllabus.repository";
import type { QuestionBlock } from "./segmenter";

export interface ConceptMapping {
  subjectId: string;
  /** Subject.code, e.g. "OS" — recorded so a reviewer can verify the tag→subject step. */
  subjectCode: string;
  unitId: string;
  topicId: string;
  conceptIds: string[];
  /** 0..1 — the score of the winning match. */
  confidence: number;
  /** How the match was made, for the review UI. */
  matchedOn:
    | "section-title"
    | "chapter-title"
    | "tag"
    | "none"
    /** A model proposed the name and the deterministic matcher confirmed it
     * exists in the syllabus. Never treated as authoritative. */
    | "assisted-exact";
  /** Human-readable reason, shown to the reviewer. */
  rationale: string;
}

/**
 * GO's subject tag (printed under every block, e.g. `operating-system`) to
 * this app's Subject.code. GO tags are the most reliable signal available:
 * they are machine-generated by the PDF pipeline, whereas the section titles
 * are free text.
 */
const TAG_TO_SUBJECT_CODE: Record<string, string> = {
  "discrete-mathematics": "MATH",
  "engineering-mathematics": "MATH",
  "linear-algebra": "MATH",
  calculus: "MATH",
  probability: "MATH",
  "graph-theory": "MATH",
  "mathematical-logic": "MATH",
  combinatorics: "MATH",
  "set-theory": "MATH",
  "numerical-methods": "MATH",
  "theory-of-computation": "TOC",
  "digital-logic": "DL",
  "co-and-architecture": "COA",
  "computer-organization": "COA",
  "data-structures": "PDS",
  programming: "PDS",
  "programming-in-c": "PDS",
  algorithms: "ALGO",
  "compiler-design": "CD",
  "operating-system": "OS",
  databases: "DBMS",
  "computer-networks": "CN",
  "general-aptitude": "GA",
  "quantitative-aptitude": "GA",
  "verbal-aptitude": "GA",
  "analytical-aptitude": "GA",
  "logical-reasoning": "GA",
  "spatial-aptitude": "GA",
  "verbal-ability": "GA",
};

/**
 * Terms where the GO section title and the syllabus wording genuinely differ,
 * so lexical similarity alone would fail. Keys are normalised GO section
 * titles (or a distinctive prefix of one); values are the syllabus entity
 * names they should be matched against.
 */
const SYNONYMS: Record<string, string[]> = {
  "process scheduling": ["CPU scheduling", "Process Management I"],
  "cpu scheduling": ["CPU scheduling"],
  "process synchronization": ["Synchronization"],
  semaphore: ["Synchronization"],
  "inter process communication": ["Inter-process communication"],
  "inter-process communication": ["Inter-process communication"],
  "fork system call": ["Processes"],
  "system calls": ["Processes"],
  threads: ["Threads"],
  "context switch": ["Threads"],
  "process state": ["Processes"],
  disk: ["I/O systems", "Device management"],
  "disk scheduling": ["I/O systems", "Device management"],
  "file system": ["File systems", "File management"],
  "linked allocation": ["File systems", "Memory allocation concepts"],
  "memory management": ["Memory management"],
  "virtual memory": ["Virtual memory"],
  "page replacement": ["Virtual memory", "Address-space management"],
  "optimal page replacement": ["Virtual memory"],
  "multilevel paging": ["Virtual memory", "Address-space management"],
  deadlock: ["Deadlock concepts"],
  "deadlock prevention avoidance detection": ["Deadlock handling"],
  "resource allocation": ["Deadlock avoidance and related techniques", "Deadlock handling"],
  "resource allocation graph": ["Deadlock concepts"],
  "precedence graph": ["Deadlock concepts"],
  "os protection": ["Other operating-system concepts"],
  "input output": ["I/O systems"],
  "io handling": ["I/O systems", "Device management"],
  interrupts: ["I/O systems", "Device management"],
  "srtf": ["CPU scheduling"],
  "subnetting": ["Subnetting and Addressing"],
  "sliding window": ["Flow and Error Control", "Sliding Window"],
  "stop and wait": ["Flow and Error Control"],
  "token bucket": ["Congestion Control", "TCP/IP protocol suite"],
  "sockets": ["Application layer protocols", "TCP/IP protocol suite"],
  "quick sort": ["Sorting"],
  "topological sort": ["Graph traversal"],
  "recurrence relation": ["Recurrence relations"],
  "reduction": ["Reducibility", "Decidability"],
  "pumping lemma": ["Regular languages", "Context-free languages"],
  "variable scope": ["Binding"],
  "register allocation": ["Code generation and optimization"],
  "static single assignment": ["Code generation and optimization"],
  "symbol table": ["Compiler phases", "Compilation process"],
  "speedup": ["Parallel processing"],
  "register": ["Registers"],
};

function normalize(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

/** Jaccard-on-tokens, matching the app's existing matcher so that scores are
 * comparable between the two paths. */
function similarity(a: string, b: string): number {
  const ta = new Set(normalize(a).split(" ").filter(Boolean));
  const tb = new Set(normalize(b).split(" ").filter(Boolean));
  if (ta.size === 0 || tb.size === 0) return 0;
  let overlap = 0;
  for (const tok of ta) if (tb.has(tok)) overlap++;
  const jaccard = overlap / new Set([...ta, ...tb]).size;

  // Plain Jaccard punishes a short section title against a longer syllabus
  // name: "Subnetting" vs "Subnetting and Addressing" scores 0.33 and would
  // fall under the floor even though it is an exact subset. Treat containment
  // in either direction as strong evidence, just below a literal match.
  const queryInCandidate = [...ta].every((t) => tb.has(t));
  const candidateInQuery = [...tb].every((t) => ta.has(t));
  if (queryInCandidate || candidateInQuery) return Math.max(jaccard, 0.75);
  return jaccard;
}

interface Candidate {
  subjectId: string;
  unitId: string;
  topicId: string;
  conceptId?: string;
  label: string;
  kind: "unit" | "topic" | "concept";
}

export function subjectCodeFromTags(tags: string[]): string | null {
  for (const tag of tags) {
    const code = TAG_TO_SUBJECT_CODE[normalize(tag).replace(/\s+/g, "-")];
    if (code) return code;
  }
  return null;
}

/** Subject codes this app actually has, so an adapter's free-text hint can be
 * validated before it is allowed to scope a match. */
export function isKnownSubjectCode(code: string): boolean {
  return SUBJECT_CODES.has(code.toUpperCase());
}

const SUBJECT_CODES = new Set(Object.values(TAG_TO_SUBJECT_CODE));

/** Normalises a free-text subject hint (an adapter sees "Database Management
 * System", the app stores "DBMS") into a known Subject.code. */
export function subjectCodeFromHint(hint: string | null | undefined): string | null {
  if (!hint) return null;
  const upper = hint.trim().toUpperCase();
  if (SUBJECT_CODES.has(upper)) return upper;
  return TAG_TO_SUBJECT_CODE[normalize(hint).replace(/\s+/g, "-")] ?? null;
}

/** A free-text query plus the label to record when it produces the match. */
export interface MappingQuery {
  text: string;
  matchedOn: ConceptMapping["matchedOn"];
}

/**
 * Resolves a question block to syllabus IDs.
 *
 * Resolution is deliberately two-stage and conservative:
 *  1. the GO subject tag picks the subject, which is deterministic;
 *  2. the section title — then the chapter title — is matched against that
 *     subject's units/topics/concepts, first through the synonym table and
 *     then through token similarity, falling back to the app's own
 *     `resolveEntity` matcher.
 *
 * Anything below MIN_CONFIDENCE returns null so the caller keeps the draft
 * unresolved rather than filing a question under a wrong topic.
 */
/**
 * Splits a `SUBJECT_CODE:name` catalog entry. Returns null when there is no
 * usable prefix or no name, so a model that returns prose, an empty string, or
 * a bare unit name resolves to nothing rather than to a wrong subject.
 *
 * Only the first colon is treated as the separator: syllabus names contain
 * colons of their own (e.g. "File Systems: allocation").
 */
export function parseCatalogLabel(label: string | null | undefined): {
  code: string;
  name: string;
} | null {
  if (!label) return null;
  const sep = label.indexOf(":");
  if (sep <= 0) return null;
  const code = label.slice(0, sep).trim().toUpperCase();
  const name = label.slice(sep + 1).trim();
  if (!code || !name) return null;
  return { code, name };
}

export function createConceptMapper(syllabusVersionId: string) {
  let candidates: Candidate[] | null = null;

  async function loadCandidates(): Promise<Candidate[]> {
    if (candidates) return candidates;
    const subjects = await syllabusRepo.findSyllabusTreeRows(syllabusVersionId);
    const out: Candidate[] = [];
    for (const s of subjects) {
      for (const u of s.units) {
        out.push({ subjectId: s.id, unitId: u.id, topicId: u.topics[0]?.id ?? "", label: u.name, kind: "unit" });
        for (const t of u.topics) {
          out.push({ subjectId: s.id, unitId: u.id, topicId: t.id, label: t.name, kind: "topic" });
          for (const c of t.concepts) {
            out.push({
              subjectId: s.id,
              unitId: u.id,
              topicId: t.id,
              conceptId: c.id,
              label: c.name,
              kind: "concept",
            });
          }
        }
      }
    }
    candidates = out;
    return out;
  }

  const MIN_CONFIDENCE = 0.34;

  /** The subject row for a code, or null when the code is not in the syllabus. */
  async function subjectByCode(code: string | null) {
    if (!code) return null;
    const rows = await syllabusRepo.findSyllabusTreeRows(syllabusVersionId);
    return rows.find((s) => s.code === code) ?? null;
  }

  /**
   * The source-agnostic matcher. `subjectCode` scopes the search; `queries`
   * are tried in order and the first one clear of MIN_CONFIDENCE wins.
   */
  async function mapHints(
    subjectCode: string | null,
    queries: MappingQuery[]
  ): Promise<ConceptMapping | null> {
    if (!subjectCode) return null;
    const all = await loadCandidates();

    // Scope every match to the mapped subject's own subtree.
    const subjectRows = await syllabusRepo.findSyllabusTreeRows(syllabusVersionId);
    const subject = subjectRows.find((s) => s.code === subjectCode);
    if (!subject) return null;

    const scoped = all.filter((c) => c.subjectId === subject.id);
    const usable = queries.filter((q) => q.text.trim());

    for (const query of usable) {
      const norm = normalize(query.text);
      const synonyms = new Set<string>();
      for (const [key, values] of Object.entries(SYNONYMS)) {
        if (norm.includes(key)) for (const v of values) synonyms.add(normalize(v));
      }

      let best: { cand: Candidate; score: number } | null = null;
      for (const cand of scoped) {
        const candNorm = normalize(cand.label);
        // A synonym hit is a strong signal but still needs to win on score.
        const boosted = synonyms.has(candNorm) ? 1 : 0;
        const score = Math.max(similarity(query.text, cand.label), boosted);
        // Prefer more specific entities when scores tie.
        const depthBonus = cand.kind === "concept" ? 0.02 : cand.kind === "topic" ? 0.01 : 0;
        const total = score + depthBonus;
        if (total > 0 && (!best || total > best.score)) best = { cand, score: total };
      }

      if (best && best.score >= MIN_CONFIDENCE) {
        return {
          subjectId: best.cand.subjectId,
          subjectCode: subject.code,
          unitId: best.cand.unitId,
          topicId: best.cand.topicId,
          conceptIds: best.cand.conceptId ? [best.cand.conceptId] : [],
          confidence: Number(best.score.toFixed(3)),
          matchedOn: query.matchedOn,
          rationale: `"${query.text}" -> ${best.cand.kind} "${best.cand.label}" (score ${best.score.toFixed(2)})`,
        };
      }
    }

    // Last resort: the app's own matcher, scoped by requiring its subject to
    // agree with the hint-derived subject.
    for (const query of usable) {
      const resolved = await resolveEntity(syllabusVersionId, query.text);
      if (resolved && resolved.subjectId === subject.id && resolved.unitId && resolved.topicId) {
        return {
          subjectId: resolved.subjectId,
          subjectCode: subject.code,
          unitId: resolved.unitId,
          topicId: resolved.topicId,
          conceptIds: resolved.conceptId ? [resolved.conceptId] : [],
          confidence: Number(resolved.confidence.toFixed(3)),
          matchedOn: query.matchedOn,
          rationale: `resolveEntity("${query.text}") -> ${resolved.matchedOn} @ ${resolved.confidence.toFixed(2)}`,
        };
      }
    }

    return null;
  }

  /**
   * Every syllabus name that could apply to this subject, as `CODE:name`.
   *
   * `subjectCode` here is the *exam paper* hint, not a syllabus subject. A
   * paper like GATE CS is one subject to the source and ten to the syllabus, so
   * scoping candidates to a single syllabus subject would leave the classifier
   * with nothing to choose from — which is exactly why the archive mapped 1 of
   * 65 questions. The prefix is what keeps the choice auditable: the model
   * returns "OS:Process Synchronization" and the reviewer can see both parts.
   */
  async function candidateCatalog(subjectCode: string | null): Promise<string[]> {
    const rows = await syllabusRepo.findSyllabusTreeRows(syllabusVersionId);
    const subject = rows.find((s) => s.code === subjectCode) ?? null;
    const scoped = subject ? [subject] : rows;
    const out: string[] = [];
    for (const s of scoped) {
      for (const u of s.units) {
        out.push(`${s.code}:${u.name}`);
        for (const t of u.topics) {
          out.push(`${s.code}:${t.name}`);
          for (const c of t.concepts) out.push(`${s.code}:${c.name}`);
        }
      }
    }
    return [...new Set(out)].sort();
  }

  /** Resolves a `CODE:name` pick from the catalog back to syllabus IDs. The
   * subject code is applied as a filter, so a model that crosses subjects is
   * corrected rather than trusted. */
  async function mappingFromCatalog(label: string): Promise<ConceptMapping | null> {
    const picked = parseCatalogLabel(label);
    if (!picked) return null;
    const subject = await subjectByCode(picked.code);
    if (!subject) return null;

    const all = await loadCandidates();
    const target = normalize(picked.name);
    const exact = all.find((c) => c.subjectId === subject.id && normalize(c.label) === target);
    if (!exact) return null;
    const { code } = picked;

    return {
      subjectId: exact.subjectId,
      subjectCode: subject.code,
      unitId: exact.unitId,
      topicId: exact.topicId,
      conceptIds: exact.conceptId ? [exact.conceptId] : [],
      // Assisted picks score below the deterministic bar: the app treats them
      // as a suggestion a reviewer confirms, never as a confident match.
      confidence: 0.5,
      matchedOn: "assisted-exact",
      rationale: `assisted classification -> ${code}:${exact.label} (${exact.kind}, unverified; reviewer must confirm)`,
    };
  }

  /** Resolves the names chosen by the assisted step into IDs, scoped to the
   * subject so a stale or mismatched pick cannot cross subjects. */
  async function mappingFromNames(
    subjectCode: string | null,
    names: string[]
  ): Promise<ConceptMapping | null> {
    const subject = await subjectByCode(subjectCode);
    if (!subject || names.length === 0) return null;
    const all = await loadCandidates();
    const scoped = all.filter((c) => c.subjectId === subject.id);

    for (const name of names) {
      const target = normalize(name);
      if (!target) continue;
      const exact = scoped.find((c) => normalize(c.label) === target);
      if (!exact) continue;
      return {
        subjectId: exact.subjectId,
        subjectCode: subject.code,
        unitId: exact.unitId,
        topicId: exact.topicId,
        conceptIds: exact.conceptId ? [exact.conceptId] : [],
        // The assisted step is a suggestion, so the score is fixed below the
        // deterministic bar for certainty and reads as such in the UI.
        confidence: 0.5,
        matchedOn: "assisted-exact",
        rationale: `assisted classification -> ${exact.kind} "${exact.label}" (unverified; reviewer must confirm)`,
      };
    }
    return null;
  }

  const mapBlock = (block: QuestionBlock) =>
    mapHints(subjectCodeFromTags(block.tags), [
      { text: block.sectionTitle ?? "", matchedOn: "section-title" },
      { text: block.topicTitle ?? "", matchedOn: "tag" },
      { text: block.chapterTitle ?? "", matchedOn: "chapter-title" },
    ]);

  return Object.assign(mapBlock, { mapHints, candidateCatalog, mappingFromCatalog });
}
