import { describe, expect, it } from "vitest";
import catalog from "@/server/domains/ingestion/catalog/gopdfs-units.json";
import type { UnitCatalogFile } from "@/server/domains/ingestion/catalog/types";

/**
 * The committed catalog is what `/api/ingestion/gopdfs/units` serves, and it is
 * regenerated by a script rather than by the app. These checks are the safety
 * net for that arrangement: a bad regeneration (a dropped release, duplicate
 * ids, a unit listing no blocks) would otherwise only show up as a confusing
 * review screen.
 */

const file = catalog as UnitCatalogFile;

describe("committed GO-PDFs unit catalog", () => {
  it("has at least one release", () => {
    expect(file.releases.length).toBeGreaterThan(0);
  });

  it("records when it was generated", () => {
    expect(Number.isNaN(Date.parse(file.generatedAt))).toBe(false);
  });

  it("gives every unit a unique id within its release, including across volumes", () => {
    for (const release of file.releases) {
      const ids = release.units.map((u) => u.id);
      expect(new Set(ids).size, `${release.release} has duplicate unit ids`).toBe(ids.length);
    }
  });

  it("keeps the printed section number alongside any volume-prefixed id", () => {
    for (const release of file.releases) {
      for (const unit of release.units) {
        // A prefixed id must still expose the bare number, or the CLI's
        // shorthand lookup and the UI's label both lose the thing a human
        // recognises.
        expect(unit.section).toMatch(/^\d+\.\d+$/);
        expect(unit.id.endsWith(unit.section)).toBe(true);
      }
    }
  });

  it("does not list a unit with no questions", () => {
    for (const release of file.releases) {
      for (const unit of release.units) {
        expect(unit.blockCount, `${release.release}/${unit.id}`).toBeGreaterThan(0);
      }
    }
  });

  it("never claims more fully-textual blocks than it has blocks", () => {
    for (const release of file.releases) {
      for (const unit of release.units) {
        expect(unit.fullyTextual).toBeLessThanOrEqual(unit.blockCount);
        expect(unit.fullyTextual).toBeGreaterThanOrEqual(0);
      }
    }
  });

  it("agrees with its own totals", () => {
    for (const release of file.releases) {
      expect(release.totals.units).toBe(release.units.length);
      expect(release.totals.blocks).toBe(release.units.reduce((n, u) => n + u.blockCount, 0));
      expect(release.totals.fullyTextual).toBe(release.units.reduce((n, u) => n + u.fullyTextual, 0));
    }
  });

  it("does not freeze per-database state into the file", () => {
    // `alreadyStaged` is computed live by the API. If it ever appears here, the
    // file has started describing one database and gone stale for every other.
    for (const release of file.releases) {
      for (const unit of release.units) {
        expect(unit).not.toHaveProperty("alreadyStaged");
      }
    }
  });

  it("gets the gatecse-2026 section counts right, matching GO's printed TOC", () => {
    const release = file.releases.find((r) => r.release === "gatecse-2026");
    expect(release, "gatecse-2026 should be cataloged").toBeDefined();

    // The first volume opens with discrete maths, whose TOC prints these
    // counts. If segmentation drifts, these are the first numbers to move.
    const byId = new Map(release!.units.map((u) => [u.id, u]));
    expect(byId.get("volume1:1.1")?.blockCount).toBe(4);
    expect(byId.get("volume1:1.2")?.blockCount).toBe(22);
    expect(byId.get("volume1:1.2")?.label).toBe("Combinatory");
    expect(byId.get("volume1:2.4")?.blockCount).toBe(40);
  });
});
