import { NextResponse } from "next/server";
import { withUser } from "@/server/http/api";
import catalogFile from "@/server/domains/ingestion/catalog/gopdfs-units.json";
import type { UnitCatalogFile } from "@/server/domains/ingestion/catalog/types";
import { listGopdfsReleases } from "@/server/domains/ingestion/gopdfs-import.service";
import { listStagedUnits } from "@/server/domains/ingestion/review.service";

export const dynamic = "force-dynamic";

const catalog = catalogFile as UnitCatalogFile;

/**
 * GET /api/ingestion/gopdfs/units?release=gatecse-2026
 *
 * The unit-wise catalog for one GO-PDFs release: every printed section of every
 * volume, with how many questions it holds and how many are already staged.
 *
 * The section structure comes from a committed file, not from parsing the PDFs
 * on request. Parsing gatecse-2026 is 45 MB of download and ~60s of CPU, which
 * has no business in a request — and PDF.js cannot be bundled into a
 * serverless function at all. The file is regenerated by
 * `scripts/build-unit-catalog.ts` when a release changes; the staged counts are
 * queried live, because those change with every import and review decision.
 *
 * Read-only on purpose. Importing is a `--release ... --unit ...` CLI run: it
 * stages thousands of rows, which does not fit in an invocation. What the
 * browser gets is the catalog plus the exact command to run.
 *
 * With no `release`, returns the release tags the GitHub repo offers.
 */
export const GET = withUser(async (_userId, req) => {
  const params = new URL(req.url).searchParams;
  const release = params.get("release");

  if (!release) {
    return NextResponse.json({
      releases: await listGopdfsReleases(),
      catalogedReleases: catalog.releases.map((r) => r.release),
      generatedAt: catalog.generatedAt,
    });
  }

  const entry = catalog.releases.find((r) => r.release === release);
  if (!entry) {
    return NextResponse.json(
      {
        error: `No unit catalog for "${release}". Run scripts/build-unit-catalog.ts --release ${release} to add it.`,
        catalogedReleases: catalog.releases.map((r) => r.release),
      },
      { status: 404 }
    );
  }

  // Live staged counts, keyed by source unit.
  const staged = await listStagedUnits({ adapterId: "gopdfs", releaseTag: release });
  const stagedByUnit = new Map(staged.map((s) => [s.sourceUnitId, s]));

  const units = entry.units.map((u) => ({
    ...u,
    alreadyStaged: stagedByUnit.get(u.id)?.total ?? 0,
    readyToApprove: stagedByUnit.get(u.id)?.ready ?? 0,
  }));

  return NextResponse.json({
    release,
    generatedAt: catalog.generatedAt,
    units,
    totals: {
      ...entry.totals,
      alreadyStaged: units.reduce((n, u) => n + u.alreadyStaged, 0),
      readyToApprove: units.reduce((n, u) => n + u.readyToApprove, 0),
    },
    importCommands: {
      oneUnit: `npm run ingest -- --source gopdfs --release ${release} --unit <unitId>`,
      everyUnit: `npm run ingest -- --source gopdfs --release ${release}`,
    },
  });
});
